# Generated by Django 3.2.5 on 2021-09-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Admin_Panel',
            name='picture',
        ),
    ]
